### ISSUE TITLE
Metric helpers

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#124]
Implement helpers to easily send custom metrics to AppSignal without having to understand OpenTelemetry metrics.

Ideally expose the same API as the Ruby implementation: https://docs.appsignal.com/metrics/custom.html#gauge

Note that we currently only support OpenTelemetry counters and gauges, not OpenTelemetry histograms (which would be AppSignal distribution values)

See #122 for sample data helpers. Will be documented as part of https://github.com/appsignal/appsignal-docs/issues/1492.

**Comment by tombruijn** [comment]
Also related to the metrics tracking issue https://github.com/appsignal/appsignal-python/issues/7

**Comment by tombruijn** [comment]
[Related Slack discussion](https://appsignal.slack.com/archives/C055A2H9NPJ/p1693919028620929) about how to make gauges work that have a somewhat similar API to our other AppSignal integrations.
