### ISSUE TITLE
Demo CLI should have --environment option

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-python#138]
Allow people to specify the app environment via the CLI. It now defaults to `development` which is not always what people want. And we don't want people to have to use the env var either.

- [ ] Add `--environment` CLI config option to diagnose command.
- [x] Add `--environment` CLI config option to demo command.
- [x] Update demo CLI docs: https://docs.appsignal.com/python/command-line/demo.html
- [x] Update docs examples: https://docs.appsignal.com/support/debugging.html

**Comment by tombruijn** [comment]
The diagnose command doesn't have any of the `--application` or `--push-api-key` options, so maybe it's not a good idea to add `--environment` either. Instead load the config file in #142 to load the config.

**Comment by tombruijn** [comment]
I think there's less of a need to add the `environment` option to the diagnose CLI. Let's revisit it when we run into it. Closing.

**Comment by unflxw** [comment]
@tombruijn Agreed. In Ruby, it makes sense to have the `--environment` option, as the configuration that is loaded from `appsignal.yml` can be different for each environment. That's not how it works here.
