### ISSUE TITLE
Research and document how to use Django with AppSignal in production

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#178]
Intercom conversation: https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/5246522/conversation/16410700274092#part_id=comment-16410700274092-21909541736

This issue should be in either appsignal/test-setups or appsignal/appsignal-docs. So it is here instead. 🙃 

Our current instructions tell you to add `appsignal.start()` to `manage.py`, which is only used during development. In production, Django recommends [deploying it as a WSGI or ASGI server](https://docs.djangoproject.com/en/4.2/howto/deployment/). When doing so, `manage.py` is never called.

Django automatically creates `wsgi.py` and `asgi.py` files for your Django project (see our existing test setup) so adding `appsignal.start()` there _might_ work? We should find out how it works, add test setups for it, then document it.

### To do

- Create test setups for Django: https://github.com/appsignal/test-setups/pull/190
  - [x] using a WSGI server
  - [x] using an ASGI server
- [x] Document how to add `appsignal.start()` when using Django with a WSGI/ASGI server for production use

**Comment by tombruijn** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/540709/conversation/16410700282044#part_id=comment-16410700282044-21909547134

**Comment by unflxw** [comment]
Another affected customer: https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/16410700293724

Bumping this to the top of to-do since I'm on support this week and it shouldn't be a tough one.
