### ISSUE TITLE
Support Pika

### ISSUE THREAD

**Issue by Nualadoyle** [appsignal/appsignal-python#181]
Requested by a customer on 30th November

> 1) Will Pika support (https://pika.readthedocs.io/en/stable/) happening soon for python performance insights?

- [Intercom](https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700274820#part_id=comment-16410700274820-21909542594)
- [OpenTelemetry package for Pika](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pika)

**Comment by luismiramirez** [comment]
Pika support added in v1.3.7

- https://pypi.org/project/appsignal/1.3.7/
- https://docs.appsignal.com/python/instrumentations/pika.html
