### ISSUE TITLE
[Question] Manually Flush logging and traces 

### ISSUE THREAD

**Issue by Felipe-RA** [appsignal/appsignal-python#221]
Greetings,

I'm using `AppSignal` to log metrics and traces for my `Serverless` Application.

While testing with  **Serverless Offline** all the lambda functions report really great on my AppSignal Dashboard.

But while my application is deployed at AWS, no error or metric shows at AppSignal (they show at CloudWatch log groups instead)

I suspect that the problem is that the AppSignal Agent does not have enough time to flush it's content to AppSignal before the lambda dies.

Can I flush all the logging manually, somehow?

This is how I imagine it:

```python
name="my-app-name"
environment="my-ENV"

appsignal = Appsignal(
    active=True,
    name=name,
    environment=environment,
    push_api_key= "MY-KEY"
)

appsignal.start()


try:

  ### ... app logic 

except:

  ### code to format the error response

finally:

  appsignal.flush() #  to manually send any opentelemetry and other traces/metrics to AppSignal
```

Is there a way to do this right now? 

Thanks for taking the time to read this!

**Comment by luismiramirez** [comment]
Hi @Felipe-RA!

You can now use the `appsignal.stop()` method from AppSignal for Python v1.3.9

**Comment by Felipe-RA** [comment]
Thank you @luismiramirez  !
