### ISSUE TITLE
appsignal-agent memory leak

### ISSUE THREAD

**Issue by sethbuff** [appsignal/appsignal-python#228]
We are noticing an issue where it appears the the Appsignal agent has a memory leak.

Our devops team notified us that one of our pods our Kubernetes cluster was infinitely growing in memory until it would restart. This has been consistently happening through multiple restarts.

We have other pods that are also running the Appsignal agent that are not having this error. There is no obvious difference in how this is being ran.

When investigating, the found a process with name: `appsignal-agent` was using about 4gb of ram.

This is running on ARM.

I'm wondering if this is something that anyone has ran into before? Or if there is an obvious answer to why this is happening?

**Comment by unflxw** [comment]
Hi @sethbuff,

That should definitely not happen. Could you reach out over at `support@appsignal.com`? We'd be interested in taking a look at the contents of the `/tmp/appsignal.log` file in the affected pod.

To confirm, is the affected pod using the AppSignal for Python integration, a different AppSignal integration, or the AppSignal stand-alone agent? And are the unaffected pods also using the AppSignal for Python integration?

**Comment by sethbuff** [comment]
I can do that!

All pods are using the AppSignal for python integration. We are also starting it the same way in all the pods using `appsignal.start()`

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700367607?view=List (private link)

**Comment by sethbuff** [comment]
Just following up...

This issue was caused by us instrumenting a long running process. We accidentally instrumented the entry point function of one of our workers which would never close. That caused the memory to grow indefinitely.

We solved the issue be removing the instrumentation of that function.

**Comment by tombruijn** [comment]
I followed up on Intercom. Let's close the issue here for now. If this is an issue in the agent, let's create a new issue in that (private) repository.

**Comment by tombruijn** [comment]
Issue resolved in our support chat. The thing that caused the perceived memory leak was a trace that never closed. The trace's root span was started at the time the process started and would only close if the process ended. The process did not have a predicatable life time, it would just keep running until a new version would be deployed or god forbid it crashed. Instead of instrumenting the entire lifetime of the process, the solution was to start a new trace per tick or item processed.

Code example:

```python
class Worker:
    def process_queued_items():
        # Start new trace here

    def run():
        # Do not start a trace here
        while True:
            self.process_queued_items()
```
