### ISSUE TITLE
Running multiple apps on one machine

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#27]
Currently, if you run multiple AppSignal for Python apps in the same machine with different configurations, only one agent will be able to report data, as only one agent will be able to listen for OpenTelemetry traces on port 8099.

[They will also step over each other as they will share the same working directory, but this will be fixable once #16 implements `working_dir_path`.]

We discussed this in [this Slack conversation](https://appsignal.slack.com/archives/C055A2H9NPJ/p1682517756326009?thread_ts=1682515629.047589&cid=C055A2H9NPJ). The easy fix is to implement some sort of `opentelemetry_port` config option.

This issue already exists in the Python OpenTelemetry setup, so it's not a blocker for release.

## To do

- [x] Add `opentelemetry_port` config option to:
  - [x] Agent config, see also `statsd_port` config option for an example
  - [x] Python package: https://github.com/appsignal/appsignal-python/pull/118
- [x] Document
  - [x] Config option in Python
  - [x] The need for `opentelemetry_port` and `working_directory_path` config options to be set and how (unique per app).

**Comment by tombruijn** [comment]
Python package 0.2.2 released along with docs updates (currently deploying at time of writing) on how to make this work: https://docs.appsignal.com/guides/application/multiple-applications-on-one-host.html
