### ISSUE TITLE
First release for Python package

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#3]
Releasing an alpha version of the package to PyPI would allow us to test the publishing process, give us confidence that `pip` selects the right package based on the combination platform tag, and it's a necessary step towards getting this to a state where customers can use it.

Note that PyPI has a "test register" that you can upload to and install from. We should probably use that for testing the release process: https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives

## To do

Feel free to split any of these into its own issue. It might also be convenient to do it in the opposite order -- release an alpha to PyPI first, using Hatch, then have that experience inform how Hatch support for Mono should be.

Keep in mind that the way we use Hatch is a bit unusual, so this might be less "implement Python/Hatch support for Mono" and more "implement custom scripts support for Mono"?

- [x] Release alpha to PyPI test environment
- [x] Test that the release installs correctly

**Comment by tombruijn** [comment]
Let's not make Mono support a blocker. We can do the first couple releases manually.

**Comment by tombruijn** [comment]
> Keep in mind that the way we use Hatch is a bit unusual, so this might be less "implement Python/Hatch support for Mono" and more "implement custom scripts support for Mono"?

I think mono already supports custom scripts for all things by customizing the `command` option for each step.
