### ISSUE TITLE
Refactor config 

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-python#36]
## To do

- [ ] Add a Config class
- [ ] That config class has an Options dict
- [ ] It stores each source (system, file/initial, env) as a separate source on the config class
- [ ] It merges the config options in the class
- [ ] It validates the config options in the class

**Comment by unflxw** [comment]
Might be done as part of #19, since it will require the sources bit.

**Comment by tombruijn** [comment]
Let's pick this up first and do the diagnose after
