### ISSUE TITLE
Support FreeBSD

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#49]
- ⚠️ Blocked on: https://github.com/appsignal/support/issues/118

Our other integrations [have FreeBSD support](https://docs.appsignal.com/support/operating-systems.html#support-table), but it was not implemented when adding other platform support because there was no easy way to test it. This issue is about implementing it and testing it the hard way, with a FreeBSD VirtualBox.

To do
---

- [ ] Add FreeBSD entry (or entries) to [the build-triple-to-platform-tag map](https://github.com/appsignal/appsignal-python/blob/main/src/scripts/platform.py#L1).
  - In this map, the key is the Rust-like build triple, [as it appears on `agent.py`](https://github.com/appsignal/appsignal-python/blob/main/src/scripts/agent.py#L123-L142), while the platform tag is ["simply"](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-tag) the output of some platform-dependent Python function in that platform, except for all the cases where it is not. 🙃 I tried looking for an existing example in PyPI's package list, filtering by the FreeBSD support category, but couldn't find one. You may need to boot a FreeBSD machine to figure out what the right value is.
  - If you can figure out if the "manylinux" spec somehow applies for FreeBSD, that would be neat, as it would allow us to specify which libc we depend on. I don't think it does, though.
- [ ] Release a build with FreeBSD artifacts to TestPyPI.
- [ ] Test with a FreeBSD virtual machine that `pip install appsignal` (with the `--index-url` bits to force installation from TestPyPI) installs the right version of the package. Make sure the agent boots.

Alternative todo list if the above is ETOOHARD:
- [ ] Change the [supported operating systems table in the docs](https://docs.appsignal.com/support/operating-systems.html#support-table) to specify that Python does not support FreeBSD.

**Comment by unflxw** [comment]
@tombruijn I'm not sure what `platform.platform()` is. [The internet says](https://stackoverflow.com/questions/71664875/what-is-the-replacement-for-distutils-util-get-platform) that `sysconfig.get_platform()` is the replacement we should look at. In my local machine, these give slightly different results to `platform.platform()`:

```
>>> import distutils; distutils.util.get_platform()
'macosx-12.6-x86_64'
>>> import sysconfig; sysconfig.get_platform()
'macosx-12.6-x86_64'
>>> import platform; platform.platform()
'macOS-12.6-x86_64-i386-64bit'
```

I'm also not sure about the current `macOS` versions specified. I cargo-culted them from _somewhere_. I don't think we need to specify them exhaustively, but [it does seem that they matter somewhat](https://packaging.pypa.io/en/stable/tags.html#packaging.tags.mac_platforms).

Some old conversations online imply that [the value provided by `distutils.util.get_platform()` is not useful for FreeBSD](https://github.com/pypa/pip/issues/2875#issuecomment-338159149). That, combined with the fact that I've not been able to find any package for FreeBSD published on PyPI (not even `numpy`, which is probably the most popular Python package with a C extension) and that [popular Python packages seem to be published as FreeBSD ports](https://www.freshports.org/math/py-numpy), makes me think that this might not be feasible. It might be that the best we can do is publish a link to a `.whl` somewhere for manual install.

Of course, I don't really know, because the documentation around all of this is incomplete and inaccurate and outdated. It's quite frustrating.

**Comment by tombruijn** [comment]
Before we ship anything, this issue is blocked on general FreeBSD support in https://github.com/appsignal/support/issues/118
