### ISSUE TITLE
Implement Flask instrumentation support

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#9]
A Flask [OpenTelemetry instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask) exists, and supporting it would be neat. If Django is Rails, then Flask is Sinatra: it's the "light-weight", DIY option for making a web application.

## To do

- [x] Create a test setup for the instrumentation https://github.com/appsignal/test-setups/pull/112
- [x] Write an extractor for the agent https://github.com/appsignal/appsignal-agent/pull/990
- [x] Add an instrumentation adder for the package https://github.com/appsignal/appsignal-python/pull/60
- [x] Document it for the package setup in PR https://github.com/appsignal/appsignal-docs/pull/1297/commits/6e90668a64690ba8a295d9bf28a45aacda95d4a6

**Comment by unflxw** [comment]
@luismiramirez I notice now that the to do list says "document this for the existing stand-alone-based setup". We can still do that if we think it's valuable, but now that [the future Python package docs](https://github.com/appsignal/appsignal-docs/pull/1300) are ready, we might want to only write the docs for the Python package and add them to that PR.

(We also haven't really tested this with the stand-alone setup, I don't think -- which is also fine in my view)

**Comment by tombruijn** [comment]
I suggest we write it for the new docs.

**Comment by luismiramirez** [comment]
Yep, my idea is to add the instructions to [this PR](https://github.com/appsignal/appsignal-docs/pull/1297/files)
